FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD Parking-Lot.jar /opt/Parking-Lot/
EXPOSE 8080
WORKDIR /opt/Parking-Lot/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "Parking-Lot.jar"]
